version: '3'

services:
  api:
    build: 
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api/dockervenv:/src/.venv
      - ./api:/src
    ports:
      - 8000:8000
  db:
    image: mysql:8.0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: 'demo' 
      TZ: 'Asia/Tokyo' 
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306 
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    volumes:
      - './front:/user/src/app'
    environment:
      - WDS_SOCKET_PORT=0
    command: sh -c "yarn start"
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true
volumes:
  mysql_data:
